livery = {


--Diffuse  -----------------------------------

{"HB_F14_EXT_01", 0 ,"HB_F14_EXT_01_VF-41_100",false};
{"HB_F14_EXT_01", ROUGHNESS_METALLIC ,"HB_F14_EXT_01_RoughMet",false};
{"HB_F14_EXT_02", 0 ,"HB_F14_EXT_02_VF-41_100",false};
{"HB_F14_EXT_02", ROUGHNESS_METALLIC ,"HB_F14_EXT_02_RoughMet",false};
{"HB_F14_EXT_03", 0 ,"HB_F14_EXT_03_VF-41_100",false};
{"HB_F14_EXT_03", ROUGHNESS_METALLIC ,"HB_F14_EXT_03_RoughMet",false};
{"HB_F14_EXT_04", 0 ,"HB_F14_EXT_04_VF-41_100",false};
{"HB_F14_EXT_04", ROUGHNESS_METALLIC ,"HB_F14_EXT_04_RoughMet",false};

{"HB_F14_EXT_TAIL", 0 ,"HB_F14_EXT_TAIL_VF-41_100",false};
{"HB_F14_EXT_TAIL", ROUGHNESS_METALLIC ,"HB_F14_EXT_TAIL_RoughMet",false};
{"HB_F14_EXT_TAIL", NORMAL_MAP ,"HB_F14_EXT_TAIL_Nrm",false};
{"HB_F14_WING_LEFT_01", 0 ,"HB_F14_WING_LEFT_VF-41_100",false};
{"HB_F14_WING_LEFT_01", ROUGHNESS_METALLIC ,"HB_F14_WING_LEFT_RoughMet",false};
{"HB_F14_WING_RIGHT", 0 ,"HB_F14_WING_RIGHT_VF-41_100",false};
{"HB_F14_WING_RIGHT", ROUGHNESS_METALLIC ,"HB_F14_WING_RIGHT_RoughMet",false};

{"HB_F14_EXT_PHOENIXRAILS", 0 ,"HB_F14_EXT_PHOENIXPYLONS_Factory",false};
{"HB_F14_EXT_PHOENIXRAILS", ROUGHNESS_METALLIC ,"HB_F14_EXT_PHOENIXPYLONS_RoughMet",false};
{"HB_F14_EXT_DROPTANKS", 0 ,"HB_F14_EXT_DROPTANK_Factory",false};
{"HB_F14_EXT_PYLONS", 0 ,"HB_F14_EXT_PYLONS_01_Factory",false};
{"HB_F14_TCS", 0 ,"HB_F14_EXT_TCS_Factory",false};
{"HB_F14_EXT_LAU-7", 0 ,"HB_F14_EXT_LAU_7",false};
{"HB_F14_EXT_INTAKERAMPS", 0,"HB_F14_EXT_INTAKERAMPS",false};

{"AIM-7M",	DIFFUSE	,"aim_7f_Diff", false};
{"AIM-7M",	ROUGHNESS_METALLIC	,"aim_7f_Diff_RoughMet", false};
{"AIM-7M",	NORMAL_MAP	,"aim_7f_Diff_Normal", false};
{"HB_F14_AIM-54", 0 ,"HB_F14_AIM-54_Early",false};

{"HB_F14_EXT_PILOT_HELMET", 0 ,"HB_F14_EXT_PILOT_HELMET",false};
{"HB_F14_EXT_PILOT_HELMET", ROUGHNESS_METALLIC ,"HB_F14_EXT_PILOT_HELMET_RoughMet",false};
{"HB_F14_EXT_PILOT_HELMET", NORMAL_MAP ,"HB_F14_EXT_PILOT_HELMET_NRM",false};
{"HB_F14_EXT_RIO_HELMET", 0 ,"HB_F14_EXT_RIO_HELMET",false};
{"HB_F14_EXT_RIO_HELMET", ROUGHNESS_METALLIC ,"HB_F14_EXT_RIO_HELMET_RoughMet",false};
{"HB_F14_EXT_RIO_HELMET", NORMAL_MAP ,"HB_F14_EXT_RIO_HELMET_NRM",false};
{"HB_F14_LOD1_3in1", 0 ,"HB_F14_LOD1_3in1_VF-41_100",false};
{"HB_F14_EXT_PILOT_SUIT", 0 ,"HB_F14_EXT_PILOT_SUIT_VF-41",false};
}
name = "IAF Nemesis Squadron(VF-42)(BLANK)(CD)"

--countries = {"USA", "RUS", "FRA", "UKR", "SPN", "NETH", "TUR", "BEL", "GER", "NOR", "CAN", "DEN", "UK", "GRG", "ISR", "ABH", "RSO"}